export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const USER_LOAD_FAIL = 'USER_LOAD_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USERS_LOADING = 'USERS_LOADING';
export const USERS_LOADED = 'USERS_LOADED';
export const USERS_LOAD_FAIL = 'USERS_LOAD_FAIL';

export const FOLLOWINGS_LOADING = 'FOLLOWINGS_LOADING';
export const FOLLOWERS_LOADING = 'FOLLOWERS_LOADING';
export const FOLLOWINGS_LOADED = 'FOLLOWINGS_LOADED';
export const FOLLOWERS_LOADED = 'FOLLOWERS_LOADED';
export const FOLLOWINGS_LOAD_FAIL = 'FOLLOWINGS_LOAD_FAIL';
export const FOLLOWERS_LOAD_FAIL = 'FOLLOWERS_LOAD_FAIL';
export const ADDING_FOLLOWING = 'ADD_FOLLOWING';
export const ADDED_FOLLOWING = 'ADD_FOLLOWING_FAIL';
export const ADD_FOLLOWING_FAIL = 'ADD_FOLLOWING_FAIL';

export const POSTS_LOADING = 'POSTS_LOADING';
export const POSTS_LOADED = 'POSTS_LOADED';
export const POSTS_LOAD_FAIL = 'POSTS_LOAD_FAIL';
export const ADD_POST = 'ADD_POST';
export const ADD_POST_FAIL = 'ADD_POST_FAIL';
export const DELETE_POST = 'DELETE_POST';

export const USER_POSTS_LOADING = 'POSTS_LOADING';
export const USER_POSTS_LOADED = 'POSTS_LOADED';
export const USER_POSTS_LOAD_FAIL = 'POST_LOAD_FAIL';

export const RETURN_ERRORS = 'RETURN_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
